# Generated by Django 5.2.8 on 2025-12-01 02:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_adminteacher_user_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)]),
        ),
    ]
