# Generated by Django 5.2.8 on 2025-11-28 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_course_is_active'),
        ('main', '0003_alter_group_name_alter_studentgroup_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='account.student'),
        ),
    ]
