# Generated by Django 5.2.8 on 2025-11-28 04:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_studentgroup_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
