# Generated by Django 5.2.8 on 2025-11-28 05:40

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_homework_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['-time'], 'verbose_name': 'homework', 'verbose_name_plural': 'homeworks'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(null=True, upload_to=main.models.lesson_video_path),
        ),
    ]
