# Generated by Django 5.2.8 on 2025-11-28 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_homework_options_alter_lesson_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='ball',
            field=models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
